### ISSUE TITLE
Error with Mongoose 5.5.14

### ISSUE THREAD

**Issue by yelworc** [alexsk/mongoose-intl#19]
Getting this error after upgrading Mongoose to v5.5.14:
```TypeError: this.getValue is not a function```

Didn't look into it thoroughly, but presumably it's caused by [this PR](https://github.com/Automattic/mongoose/pull/7870) which renamed the internal method `getValue`.
